"""nkmt

Revision ID: 0006_nkmt
Revises: 94526be42e46
Create Date: 2026-09-04 00:46:11.838635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006_nkmt'
down_revision: Union[str, Sequence[str], None] = '94526be42e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE SCHEMA IF NOT EXISTS nkmt')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_filename', sa.String(length=256), nullable=False),
    sa.Column('feed_id', sa.String(length=64), nullable=False),
    sa.Column('stats', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='nkmt'
    )
    op.create_table('brand_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='nkmt'
    )
    op.create_table('declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_number', sa.String(), nullable=False),
    sa.Column('doc_date', sa.String(length=10), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_number', 'doc_date', name='uq_doc_pair'),
    schema='nkmt'
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=64), nullable=False),
    sa.Column('gtin', sa.String(length=32), nullable=False),
    sa.Column('good_id', sa.String(length=64), nullable=False),
    sa.Column('tnved', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cat_id', sa.String(length=64), nullable=False),
    sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['nkmt.batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article'),
    schema='nkmt'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards', schema='nkmt')
    op.drop_table('declarations', schema='nkmt')
    op.drop_table('brand_cache', schema='nkmt')
    op.drop_table('batches', schema='nkmt')
    op.execute('DROP SCHEMA IF EXISTS nkmt CASCADE')
    # ### end Alembic commands ###
