"""mt external_id

Revision ID: 94526be42e46
Revises: 79f86c608c44
Create Date: 2026-09-03 15:01:32.004497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94526be42e46'
down_revision: Union[str, Sequence[str], None] = '79f86c608c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docs', sa.Column('external_id', sa.String(length=64), server_default='', nullable=False), schema='mt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docs', 'external_id', schema='mt')
    # ### end Alembic commands ###
